### ISSUE TITLE
Keycloak root doesn't need to start from /auth

### ISSUE THREAD

**Issue by splatch** [cloudtrust/keycloak-client#4]
I have no intention to use a library, however I found that sources assume that keycloak root is always `/auth`. This can be changed to all paths starts from `/ralms`. Management pane in such case is also accessible from root via `/admin` path.

**Comment by harture** [comment]
Thanks for the hint! In our current setup we do not have such customization thus it is reasonable for the time being to have it hard coded. But we could indeed make it customizable in the future.

**Comment by fperot74** [comment]
If someone wants to use this library and needs to set a different base endpoint, he/she might feel free to submit a PR.
